// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjVQ4qjUUO42eqPL_gPkDU_DDuhT9_4ms',
    appId: '1:905844914008:web:e2560e65849db3b3da572d',
    messagingSenderId: '905844914008',
    projectId: 'm2chanic',
    authDomain: 'm2chanic.firebaseapp.com',
    storageBucket: 'm2chanic.appspot.com',
    measurementId: 'G-R0Q8CZCTB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYVQSWENsbrWA4y1kj0yZA18VZ9dhq1XY',
    appId: '1:905844914008:android:5eb2ad033635fd10da572d',
    messagingSenderId: '905844914008',
    projectId: 'm2chanic',
    storageBucket: 'm2chanic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1NY53DvMVw_kVZNgZCi6cX-LHhRJ7QoI',
    appId: '1:905844914008:ios:826038265e6372aada572d',
    messagingSenderId: '905844914008',
    projectId: 'm2chanic',
    storageBucket: 'm2chanic.appspot.com',
    iosBundleId: 'com.example.mechanic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1NY53DvMVw_kVZNgZCi6cX-LHhRJ7QoI',
    appId: '1:905844914008:ios:6265d28e78c147e5da572d',
    messagingSenderId: '905844914008',
    projectId: 'm2chanic',
    storageBucket: 'm2chanic.appspot.com',
    iosBundleId: 'com.example.mechanic.RunnerTests',
  );
}
